Repository eprints/eprints3.4, pull requests merged in 2025-08, with the labels that each got.

#482 Tidy up use of 'get_citaiton_id' in search screens
  perl_lib/EPrints/Plugin/Screen/AbstractSearch.pm
  perl_lib/EPrints/Plugin/Screen/Search.pm
Labels: enhancement

#488 Implements #465 by adding uuid field to Cachemap
  perl_lib/EPrints/DataObj/Cachemap.pm
  perl_lib/EPrints/Database.pm
  perl_lib/EPrints/List.pm
  perl_lib/EPrints/Search.pm
Labels: enhancement

#489 Implements #476 by customisably showing text links for untitled subjects
  perl_lib/EPrints/DataObj/Subject.pm
  perl_lib/EPrints/Repository.pm
  perl_lib/EPrints/Update/Views.pm
Labels: enhancement

#490 Pull the 'metatags' ingredient into core
  flavours/pub_lib/cfg.d/eprint_render.pl
  flavours/pub_lib/plugins/EPrints/Plugin/Export/HighwirePress.pm
  flavours/pub_lib/plugins/EPrints/Plugin/Export/Prism.pm
  perl_lib/EPrints/MetaField/Pagerange.pm
Labels: bug, enhancement

#493 Add 'export_file_as_attachment' option to force exports to be downloaded
  cgi/export
  cgi/exportview
Labels: enhancement

#494 Fix metatag issue on EPrints without a pagerange field
  flavours/pub_lib/plugins/EPrints/Plugin/Export/HighwirePress.pm
  flavours/pub_lib/plugins/EPrints/Plugin/Export/Prism.pm
Labels: bug

#501 Fixes batch edit broken after switching to cachemap uuid (#465)
  perl_lib/EPrints/Plugin/Screen/BatchEdit.pm
Labels: bug
